<?php

namespace App\Models;

use App\Models\Student;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Model;

class College extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'address']; //Applied mass assignment to be enable the creation of a new college by sending data in the form an associative array. id() and timestamps() are not included as they are auto-generated by Laravel.

    public function students(): HasMany {
        return $this->hasMany(Student::class); //Established a one-to-many relationship between colleges and students. A college can have many students, but a student can only belong to one college.
    }
}
