<?php

namespace App\Models;

use App\Models\College;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;

/* Through the development of this Laravel application, the developer will not interact directly with the database 
to commit transactions (in this case, to perform CRUD operations on the Students table).
 * Therefore, the Student model class will serve as an intermediary to enroll students, as well as modify and deleting existing students. */
class Student extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'email', 'phone', 'dob', 'college_id']; //Applied mass assignment to be enable the creation of a new student by sending data in the form an associative array. id() and timestamps() are not included as they are auto-generated by Laravel.

    /**
     * This function is used to define a many-to-one relationship between the Student model and the College model, 
     * stating that many students can be associated with only college but a college can enroll many students. 
     * When invoking the belongsTo method, each instance of the Student model class will consist of the college_id attribute as well,
     * which links to the id attribute pertaining the College model class.
     * @return BelongsTo This type of relationship indicates a many-to-one relationship exists between Student and College. The Student model class embodies the many part of this relationship.
     */
    public function college(): BelongsTo
    {
        return $this->belongsTo(College::class); //Established a many-to-one relationship between colleges and students. This indicates that many students can be associated with a college, but only one college at a time.
    }
}